apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app-container
        image: sonbarse17/ruby-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: db-service
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: RAILS_ENV
          value: development
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
