apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  selector:
    app.kubernetes.io/name: student-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
