apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-management-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sonbarse17/student-management-ruby
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true