apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: student-app-db
spec:
  serviceName: db-service
  selector:
    matchLabels:
      app: student-app-db
  replicas: 1
  template:
    metadata:
      labels:
        app: student-app-db
    spec:
      containers:
      - name: student-app-db-container
        image: sonbarse17/ruby-db:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: student_management_development
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: psql-storage 
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: psql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 30Gi
      storageClassName: standard
