apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: db-migrate
        image: sonbarse17/ruby-app:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Waiting for database connection..."
          until pg_isready -h db-service -p 5432 -U postgres; do
            echo "Database not ready, waiting..."
            sleep 5
          done
          echo "Database ready, running migrations..."
          rails db:create db:migrate db:seed
        env:
        - name: DATABASE_HOST
          value: db-service
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: RAILS_ENV
          value: development
        - name: PGPASSWORD
          value: postgres
      restartPolicy: OnFailure
  backoffLimit: 3