apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: db-migrate
        image: sonbarse17/ruby-app:latest
        command: ["rails", "db:create", "db:migrate", "db:seed"]
        env:
        - name: DATABASE_HOST
          value: db-service
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: RAILS_ENV
          value: development
      restartPolicy: OnFailure
  backoffLimit: 3