name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: sonbarse17

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image for service1
        run: |
          docker build -f Dockerfile.service1 -t $DOCKERHUB_USERNAME/service1:latest .

      - name: Build Docker image for service2
        run: |
          docker build -f Dockerfile.service2 -t $DOCKERHUB_USERNAME/service2:latest .

      - name: Push service1 image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/service1:latest

      - name: Push service2 image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/service2:latest

