name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - 'terraform/**'

env:
  DOCKERHUB_USERNAME: sonbarse17

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image for Ruby application
        run: |
          docker build -f Dockerfile.app -t $DOCKERHUB_USERNAME/ruby-app:latest .

      - name: Build Docker image for Postgres Database
        run: |
          docker build -f Dockerfile.db -t $DOCKERHUB_USERNAME/ruby-db:latest .

      - name: Push Application image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/ruby-app:latest

      - name: Push Darabase image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/ruby-db:latest

