name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/gke

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create State Bucket
        run: |
          PROJECT_ID=$(gcloud config get-value project)
          gsutil mb gs://$PROJECT_ID-terraform-state || true
          gsutil versioning set on gs://$PROJECT_ID-terraform-state || true

      - name: Terraform Init
        run: |
          PROJECT_ID=$(gcloud config get-value project)
          terraform init \
            -backend-config="bucket=$PROJECT_ID-terraform-state" \
            -backend-config="prefix=gke/state"

      - name: Terraform Apply
        run: terraform apply -auto-approve

#Note: Uncomment the following lines to configure kubectl after applying Terraform
#gcloud container clusters get-credentials my-gke-cluster \
#  --region us-central1 \
#  --project aerial-handbook-462908-j3

#gcloud container clusters get-credentials my-gke-cluster --region us-central1 --project aerial-handbook-462908-j3


